apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-deployment
  template:
    metadata:
      name: demo-deployment
      labels:
        app: demo-deployment
    spec:
      containers:
        - name: demo-deployment
          image: demo-deploy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
